---
- name: Deploy Operator Contract
  hosts: servers  # Replace with your inventory group or specific hosts
  become: yes  # Use sudo if needed
  tasks:
    - name: Install required dependencies
      ansible.builtin.apt:
        name:
          - curl
          - build-essential
        state: present

    - name: Install NVM and Node.js
      ansible.builtin.shell: |
        # Install NVM if not already installed
        if [ ! -d "$HOME/.nvm" ]; then
          echo "Installing NVM..."
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        fi

        # Load NVM
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

        # Install Node.js if not already installed
        if ! command -v node &> /dev/null || [ "$(node --version | cut -d 'v' -f 2)" != "20.18.0" ]; then
          echo "Installing Node.js 20.18.0..."
          nvm install 20.18.0
        fi

        # Check if npm is installed
        if ! command -v npm &> /dev/null; then
          echo "Installing npm..."
          apt-get update
          apt-get install -y npm
        fi

        # Display Node.js and npm versions
        echo "Node.js version: $(node --version)"
        echo "npm version: $(npm --version)"
      args:
        executable: /bin/bash  # Ensure bash is used

    - name: Install project dependencies
      ansible.builtin.shell: |
        # Change to the working directory
        cd /tmp/ChainlinkContractsAssets/ansible/playbooks/deployContractsPlaybooks/operatorContract/assets/.deps/npm
        
        # Install Hardhat, dotenv, Hardhat Ethers, and Chainlink contracts
        echo "Installing project dependencies..."
        npm install --save-dev hardhat dotenv @nomiclabs/hardhat-ethers "ethers@^5.0.0"
        npm install @chainlink/contracts

    - name: Deploy the Operator contract
      ansible.builtin.shell: |
        # Change to the working directory
        cd /tmp/ChainlinkContractsAssets/ansible/playbooks/deployContractsPlaybooks/operatorContract/assets/.deps/npm

        # Deploy the contract
        echo "Deploying the Operator contract..."
        npx hardhat run deployments/deploy.js --network sepolia
      args:
        executable: /bin/bash  # Ensure bash is used
