---
- name: Install Prometheus on Ubuntu using Docker
  hosts: servers
  become: true
  tasks:
    - name: Update the apt package manager
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create Prometheus configuration directory
      file:
        path: /etc/prometheus
        state: directory

    - name: Create Prometheus configuration file
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          rule_files:
            - /etc/prometheus/rules.yml

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']  # Adjusted to localhost
            - job_name: 'node-exporter'
              static_configs:
                - targets: ['node_exporter:9100']    
        mode: '0644'

    - name: Create Prometheus alert rules file
      copy:
        dest: /etc/prometheus/rules.yml
        content: |
          groups:
            - name: cpu_memory_alerts
              rules:
                - alert: HighCPUUsage
                  expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 85
                  for: 2m
                  labels:
                    severity: critical
                  annotations:
                    summary: "High CPU Usage detected"
                    description: "CPU usage is above 85% for more than 2 minutes."

                - alert: HighMemoryUsage
                  expr: (node_memory_MemTotal_bytes{job="node-exporter"} - node_memory_MemAvailable_bytes{job="node-exporter"}) / node_memory_MemTotal_bytes{job="node-exporter"} * 100 > 85
                  for: 2m
                  labels:
                    severity: critical
                  annotations:
                    summary: "High Memory Usage detected"
                    description: "Memory usage is above 85% for more than 2 minutes."
        mode: '0644'

    - name: Pull Prometheus Docker image
      docker_image:
        name: prom/prometheus
        tag: latest
        source: pull

    - name: Create Prometheus container
      docker_container:
        name: prometheus
        image: prom/prometheus:latest
        state: started
        restart_policy: always
        network_mode: host
        volumes:
          - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
          - /etc/prometheus/rules.yml:/etc/prometheus/rules.yml  # Mount the rules file
        command: "--config.file=/etc/prometheus/prometheus.yml"
      register: prometheus_container
      become: yes

    - name: Restart Prometheus container to apply any config changes
      docker_container:
        name: prometheus
        state: started 
        restart_policy: always 
      when: prometheus_container.changed == false
      become: yes
